---
title: "Bee_Colony_Losses"
output: html_document
---

--------------------------------------------------------------------------------------------------------------------------
```{r  Loading Packages }
library(tidyverse)
library(lubridate)
library(highcharter)
library(RColorBrewer)
library(plotly)
library(viridis)
library(geojsonio)
library(rgdal)
library(broom)
library(rgeos)
detach(package:MASS, unload=TRUE)

```

```{r  Reading CSV files}
honey <- read_csv("Honey.csv")
honey

colony <- read_csv("Colony.csv")
colony

stressors <- read_csv("Stressors.csv")
stressors

summary(honey)

# not required to convert year numbers to date format as there is no month/day information 

sum(is.na(honey)) # no missing values in this data set 
```


```{r  Colony df: Removing rows with mostly NA values }
# 2019-Q2 seems to be missing a lot of information 
colony$`Starting Colonies` <- as.numeric(colony$`Starting Colonies`)
colony[is.na(colony$`Starting Colonies`), ]

# let's take a look at all other values in 2019-Q2 

colony %>% 
  filter(Year == "2019-Q2")

# looks like there is no information for this quarter; it would be helpful to remove these rows along with any other
# rows that have missing values in all of these numeric columns 

colony <- colony %>% 
  filter_at(vars(`Starting Colonies`, `Maximum Colonies`, `Lost Colonies`, `Percent Loss`, `Added Colonies`, `Renovated Colonies`, `Percent Renovated`), all_vars(!is.na(.)))

colony

```

```{r  Colony df: Imputing missing values, and converting character to numeric } 
# some number columns classified as character; converting chr to numeric (Starting Colonies, Maximum Colonies, Lost Colonies, Percent Loss, Added Colonies, Renovated Colonies, Percent Renovated, Year)

colony <- colony %>% 
  mutate_at(c(2:8), as.numeric)

# many NAs are now apparent in percent_renovated column because they were previously denoted as (Z) for being 0/close
# to zero. We can fill in those NA values with their calculations 

colony <- colony %>% 
  mutate(`Percent Renovated` = case_when(
    !is.na(`Percent Renovated`) ~ `Percent Renovated`, 
    is.na(`Percent Renovated`) ~ (round(`Renovated Colonies`*100/`Maximum Colonies`))
  ))

colony

sapply(colony, class)

# are there any other NA values in the data frame? 
colony[rowSums(is.na(colony)) > 0, ]

# there are some missing values in 'Percent Loss' for some states, which can be computed 
# Percent loss = number of lost colonies / max colonies 

colony <- colony %>% 
  mutate(`Percent Loss` = case_when(
    !is.na(`Percent Loss`) ~ `Percent Loss`,
    is.na(`Percent Loss`) ~ (round(`Lost Colonies`*100/`Maximum Colonies`))
  )
  )

colony[rowSums(is.na(colony)) > 0, ]

# Vermont missing data for renovated colonies 
# United States is also missing maximum colonies values; can we sum up all the states to fill in the missing values? 

# separating Year from Quarter 
colony <- colony %>% 
  separate(col= Year, into = c("Year", "Quarter", sep="-")) %>% 
  select(-c("-"))

colony

colony <- colony %>% 
  mutate_at(c(2:9), as.numeric)

sapply(colony, class)

colony

colony$Year <- factor(colony$Year)
colony$Quarter <- factor(colony$Quarter)
sapply(colony, class)

```


```{r  Colony df: Separating national colony counts from state counts, feature engineering}

# removing US values from the original colony data set 

US_colony <- colony[colony$State == 'United States',]

colony <- colony[!colony$State == 'United States',]

colony[rowSums(is.na(colony)) > 0, ]  # only Vermont showing NA values under renovated colonies and percent renovated 

US_colony

US_colony2 <- US_colony %>% 
  select(everything()) %>% 
  group_by(Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(rel_perc_loss = round((`Lost Colonies`*100 /`tot_loss`),0))

US_colony2
```


```{r  Stressors df: Cleaning Stressors dataset; converting chr to numeric, separating United States values}
summary(stressors)

sum(is.na(stressors))   # 597 missing values 

stressors[rowSums(is.na(stressors)) > 0, ]  # showing all rows that have NA values 

# Splitting Year into two columns: Year and Quarter 
stressors <- stressors %>% 
  separate(col= Year, into = c("Year", "Quarter", sep="-")) %>% 
  select(-c("-"))

stressors <- stressors %>% 
  mutate_at(c(2:8), as.numeric)

stressors$Year <- factor(stressors$Year)
stressors$Quarter <- factor(stressors$Quarter)
sapply(stressors, class)

# separating out US values into its own dataframe 
US_stressors <- stressors[stressors$State == 'United States', ]

stressors <- stressors[!stressors$State == 'United States', ]

```


```{r  Honey dataframe: checking missing values, separating US values, and adjusting Year values}
summary(honey) 

sum(is.na(honey))  # no immediately apparent NA values 

unique(honey$State)

US_honey <- honey[honey$State == 'United States', ]

honey <- honey[!honey$State == 'United States', ]

```

```{r  Visual Exploration}
US_stressors   # 25x8 
US_colony      # 25x9
US_honey       # 6x8
```
```{r  Losses over Seasons/Quarters }

US_colony2 %>% 
  ggplot(aes(x = Quarter, y = rel_perc_loss, group = Year, colour = Year)) + geom_line() + geom_point() +
  theme_bw() + 
  labs(x = "Quarter", y="Relative Percent Colony Loss", title="Relative Percent Colony Loss in the US") + 
  theme(plot.title = element_text(hjust = .5))



# We can see that for years 2015-2018 and 2020, there seems to be a seasonal type of pattern where 
# relative percent colony losses are occurring mostly in the colder months. Losses generally seem to be # lower in Q2 (Apr - Jun), then increase in the summer, before peaking in the winter months. 

# Let's look into 2021 and 2019 in more detail. Let's also see if there seems to be a cyclical pattern
# over time 
```

```{r}

US_colony2 <- US_colony2 %>% 
  mutate(Date = str_c(Year, Quarter, sep = " "))



US_colony2

US_colony2 %>% 
  ggplot(aes(x=Date, y=rel_perc_loss, fill = Quarter)) + geom_col() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(x = 'Date', y='Relative Percent Colony Loss', title = 'Relative Percent Colony Loss in the US Over Time')+
  theme(plot.title = element_text(hjust = .5)) +
  scale_fill_brewer(palette = "Paired") 


###### switch blue and green colours; blue or winter months, green for spring/summer 
###### if more time, plot a smooth line over the curves to show the seasonal trend 
```

```{r  Examining Effects of Stressors on Colony Loss}
# looking more closely at Years 2019 and 2021, we want to bring forward the stressors data
US_colony2 <- US_colony2 %>% relocate(Date, .after = Quarter)

US_stressors
US_stressors <- US_stressors %>% 
  mutate(Date = str_c(Year, Quarter, sep=" "))

US_stressors %>% 
  filter(!is.na(`Varroa Mites (Percent)`)) %>% 
  ggplot(aes(x=Date, y=`Varroa Mites (Percent)`, fill = Quarter)) + geom_col(fill = "#69b3a2") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  theme_bw() + 
  labs(x = 'Date', y='Varroa Mites (Percent)', title = 'Percentage of Colonies Across the US Infected with Varroa Mites ')+
  theme(plot.title = element_text(hjust = .5)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) 

US_stressors

```
```{r   Joining US stressors data and US colonies }

US_colony_stressors <- inner_join(US_stressors, US_colony2, by="Date")

US_colony_stressors <- US_colony_stressors %>%  
select(State.x, `Varroa Mites (Percent)`, `Other pests and parasites (Percent)`, `Diseases (percent)`, `Pesticides (percent)`, `Other (percent)`, `Unknown (percent)`, Date, `Starting Colonies`, `Lost Colonies`, `Percent Loss`, `Added Colonies`, `Renovated Colonies`, `Percent Renovated`, tot_loss, rel_perc_loss)

US_colony_stressors %>% 
  gg

```






```{r}
US_stressors
US_stressors %>% 
  filter(!is.na(`Varroa Mites (Percent)`)) %>% 
  ggplot(aes(x=Date, y=`Other pests and parasites (Percent)`, fill = Quarter)) + geom_col(fill = "#69b3a2") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) 
```

```{r  Examining Honey Production Value Over Time }

honey_overtime <- read.csv("honeyproduction.csv")

US_honeyovertime <- honey_overtime %>% 
  group_by(year) %>% 
  summarise(US_prodval = sum(prodvalue))

US_honeyovertime <- US_honeyovertime %>% 
  mutate('Value of production (1,000 dollars)' = US_prodval/1000) %>% 
  select(year, 'Value of production (1,000 dollars)') %>% 
  rename(Year = year)

US_honey_prodval <- US_honey %>% 
  select(Year, `Value of production (1,000 dollars)`)

US_honey_prodval

US_honey_overtime <- bind_rows(US_honeyovertime, US_honey_prodval)

# subbing in missing values; data extracted from USDA library website 
US_honey_overtime <- US_honey_overtime %>% 
  add_row(Year = 2013, `Value of production (1,000 dollars)`= 320037)

US_honey_overtime <- US_honey_overtime %>% 
  add_row(Year = 2014, `Value of production (1,000 dollars)`= 325946)

US_honey_overtime$`Value of production (1,000 dollars)` <- US_honey_overtime$`Value of production (1,000 dollars)`/1000

US_honey_overtime <- US_honey_overtime %>% 
  rename("Value of production (millions)" = `Value of production (1,000 dollars)` )

US_honey_overtime %>% 
  ggplot(aes(x=Year, y=`Value of production (millions)`)) + geom_col(fill = "#e3b526") +   
  labs(x = 'Year', y='Value of Production in (Million USD)', title = 'Value of Honey Production in the US Over Time') +
  theme(plot.title = element_text(hjust = .5)) 

```

```{r  Amount of honey produced in the US over time }

tot_prod <- honey_overtime %>% 
  group_by(year) %>% 
  summarise(tot_prod = sum(totalprod)/1000) %>% 
  rename(Year = year, "Production (1,000 pounds)" = tot_prod)

US_honey_prod <- US_honey %>% 
  select(Year, `Production (1,000 pounds)`)

tot_prod

US_honey_totprod <- bind_rows(US_honey_prod, tot_prod)


US_honey_totprod <- US_honey_totprod %>% 
  add_row(Year = 2013, "Production (1,000 pounds)" = 149550) %>% 
  add_row(Year = 2014, "Production (1,000 pounds)" = 178310)

US_honey_totprod <- US_honey_totprod %>% 
  arrange(Year)

US_honey_totprod

#plotting graph 
library(MASS)

US_honey_totprod %>% 
  ggplot(aes(x=Year, y= `Production (1,000 pounds)`)) + geom_col(fill = "#e3b526") +
  labs(x = 'Year', y='Honey Production (1,000 lbs)', title = 'Amount of Honey Produced in the US Over Time')+
  theme(plot.title = element_text(hjust = .5)) 
  

```


```{r  Mapping State Percent Colony Loss}

loss_2015 <- colony %>% 
  select(everything()) %>% 
  filter(Year == 2015) %>% 
  group_by(State, Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(avg_loss = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

summary(loss_2015)  # avg_loss ranges from 5.75 - 21 % for each state 



# map creation

map <- geojson_read("us_states_hexgrid.geojson", what = "sp")
map@data <-  map@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
map_fortified <- tidy(map, region = "google_name")

# calculating centroid of each hexagon and adding labels 

centers <- cbind.data.frame(data.frame(gCentroid(map, byid= TRUE), id=map@data$iso3166_2))

# merge geospatial and numerical data 
loss_2015_fortified <- map_fortified %>% 
  left_join(. , loss_2015, by=c("id" = "State"))

loss_2015_fortified

# prepare binning 
loss_2015_fortified$bin <- cut(loss_2015_fortified$avg_loss, breaks = c(seq(5,20,5), Inf), labels = c("5-10", "11-15", "16-20", "21+"), include.lowest=TRUE)

# colour scale from viridis color palette
my_palette <- rev(plasma(8))[c(-1,-8)]

# plotting 
ggplot() + 
  geom_polygon(data = loss_2015_fortified, aes(fill = bin, x = long, y= lat, group = group), size = 0, alpha = 0.9) + 
  geom_text(data = centers, aes(x=x, y=y, label=id), color="white", size = 3, alpha = 0.6) + 
  theme_void() + 
  scale_fill_manual(
    values = my_palette,
    name = "Average Percentage Colony Loss",
    guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                         label.position = "bottom", title.position = "top", nrow=1)) + 
  ggtitle("A Map of Percent Colony Loss by State in 2015") + 
  theme(
    legend.position=c(0.5, 0.9),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size=16, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4,
                                                                                     l = 2, unit = "cm")),
  )

```

```{r  State colony loss map during colder months in 2015 }
loss_2015_coldmonths <- colony %>% 
  select(everything()) %>% 
  filter((Year == 2015) & (Quarter %in% c("Q1", "Q4"))) %>% 
  group_by(State, Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(avg_loss = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

summary(loss_2015_coldmonths)  # avg_loss ranges from 5.75 - 21 % for each state 



# map creation

map <- geojson_read("us_states_hexgrid.geojson", what = "sp")
map@data <-  map@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
map_fortified <- tidy(map, region = "google_name")

# calculating centroid of each hexagon and adding labels 

centers <- cbind.data.frame(data.frame(gCentroid(map, byid= TRUE), id=map@data$iso3166_2))

# merge geospatial and numerical data 
loss_2015_coldmonths_fortified <- map_fortified %>% 
  left_join(. , loss_2015_coldmonths, by=c("id" = "State"))

loss_2015_coldmonths_fortified

# prepare binning 
loss_2015_coldmonths_fortified$bin <- cut(loss_2015_coldmonths_fortified$avg_loss, breaks = c(seq(1,32,8), Inf), labels = c("1-8", "9-16", "17-24", "25+"), include.lowest=TRUE)

# colour scale from viridis color palette
my_palette <- rev(plasma(8))[c(-1,-8)]

# plotting 
ggplot() + 
  geom_polygon(data = loss_2015_coldmonths_fortified, aes(fill = bin, x = long, y= lat, group = group),color = "white",
               size = 0, alpha = 0.9) + 
  geom_text(data = centers, aes(x=x, y=y, label=id),color="white", size = 3, alpha = 0.6) + 
  theme_void() + 
  scale_fill_manual(
    values = my_palette,
    name = "Average Percentage Colony Loss",
    guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                         label.position = "bottom", title.position = "top", nrow=1)) + 
  ggtitle("A Map of Percent Colony Loss During Colder Months by State in 2015") + 
  theme(
    legend.position=c(0.5, 0.9),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size=12, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4,
                                                                                     l = 2, unit = "cm")),
  )

```




```{r  State colony loss map during colder months in 2016} 
loss_2016_coldmonths <- colony %>% 
  select(everything()) %>% 
  filter((Year == 2016) & (Quarter %in% c("Q1", "Q4"))) %>% 
  group_by(State, Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(avg_loss = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

summary(loss_2016_coldmonths)  

# map creation

map <- geojson_read("us_states_hexgrid.geojson", what = "sp")
map@data <-  map@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
map_fortified <- tidy(map, region = "google_name")

# calculating centroid of each hexagon and adding labels 

centers <- cbind.data.frame(data.frame(gCentroid(map, byid= TRUE), id=map@data$iso3166_2))

# merge geospatial and numerical data 
loss_2016_coldmonths_fortified <- map_fortified %>% 
  left_join(. , loss_2016_coldmonths, by=c("id" = "State"))

loss_2016_coldmonths_fortified

# prepare binning 
loss_2016_coldmonths_fortified$bin <- cut(loss_2016_coldmonths_fortified$avg_loss, breaks = c(seq(1,32,8), Inf), labels = c("1-8", "9-16", "17-24", "25+"), include.lowest=TRUE)

# colour scale from viridis color palette
my_palette <- rev(plasma(8))[c(-1,-8)]

# plotting 
ggplot() + 
  geom_polygon(data = loss_2016_coldmonths_fortified, aes(fill = bin, x = long, y= lat, group = group),color = "white",
               size = 0, alpha = 0.9) + 
  geom_text(data = centers, aes(x=x, y=y, label=id),color="white", size = 3, alpha = 0.6) + 
  theme_void() + 
  scale_fill_manual(
    values = my_palette,
    name = "Average Percentage Colony Loss",
    guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                         label.position = "bottom", title.position = "top", nrow=1)) + 
  ggtitle("A Map of Percent Colony Loss During Colder Months by State in 2016") + 
  theme(
    legend.position=c(0.5, 0.9),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size=12, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4,
                                                                                     l = 2, unit = "cm")),
  )
```


```{r   State colony loss map during colder months in 2017}
loss_2017_coldmonths <- colony %>% 
  select(everything()) %>% 
  filter((Year == 2017) & (Quarter %in% c("Q1", "Q4"))) %>% 
  group_by(State, Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(avg_loss = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

summary(loss_2017_coldmonths)  

# map creation

map <- geojson_read("us_states_hexgrid.geojson", what = "sp")
map@data <-  map@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
map_fortified <- tidy(map, region = "google_name")

# calculating centroid of each hexagon and adding labels 

centers <- cbind.data.frame(data.frame(gCentroid(map, byid= TRUE), id=map@data$iso3166_2))

# merge geospatial and numerical data 
loss_2017_coldmonths_fortified <- map_fortified %>% 
  left_join(. , loss_2017_coldmonths, by=c("id" = "State"))

loss_2017_coldmonths_fortified

# prepare binning 
loss_2017_coldmonths_fortified$bin <- cut(loss_2017_coldmonths_fortified$avg_loss, breaks = c(seq(1,32,8), Inf), labels = c("1-8", "9-16", "17-24", "25+"), include.lowest=TRUE)

# colour scale from viridis color palette
my_palette <- rev(plasma(8))[c(-1,-8)]

# plotting 
ggplot() + 
  geom_polygon(data = loss_2017_coldmonths_fortified, aes(fill = bin, x = long, y= lat, group = group),color = "white",
               size = 0, alpha = 0.9) + 
  geom_text(data = centers, aes(x=x, y=y, label=id),color="white", size = 3, alpha = 0.6) + 
  theme_void() + 
  scale_fill_manual(
    values = my_palette,
    name = "Average Percentage Colony Loss",
    guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                         label.position = "bottom", title.position = "top", nrow=1)) + 
  ggtitle("A Map of Percent Colony Loss During Colder Months by State in 2017") + 
  theme(
    legend.position=c(0.5, 0.9),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size=12, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4,
                                                                                     l = 2, unit = "cm")),
  )
```
```{r  State colony loss map during colder months in 2018}
loss_2018_coldmonths <- colony %>% 
  select(everything()) %>% 
  filter((Year == 2018) & (Quarter %in% c("Q1", "Q4"))) %>% 
  group_by(State, Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(avg_loss = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

summary(loss_2018_coldmonths)  

# map creation

map <- geojson_read("us_states_hexgrid.geojson", what = "sp")
map@data <-  map@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
map_fortified <- tidy(map, region = "google_name")

# calculating centroid of each hexagon and adding labels 

centers <- cbind.data.frame(data.frame(gCentroid(map, byid= TRUE), id=map@data$iso3166_2))

# merge geospatial and numerical data 
loss_2018_coldmonths_fortified <- map_fortified %>% 
  left_join(. , loss_2018_coldmonths, by=c("id" = "State"))

loss_2018_coldmonths_fortified

# prepare binning 
loss_2018_coldmonths_fortified$bin <- cut(loss_2018_coldmonths_fortified$avg_loss, breaks = c(seq(1,32,8), Inf), labels = c("1-8", "9-16", "17-24", "25+"), include.lowest=TRUE)

# colour scale from viridis color palette
my_palette <- rev(plasma(8))[c(-1,-8)]

# plotting 
ggplot() + 
  geom_polygon(data = loss_2018_coldmonths_fortified, aes(fill = bin, x = long, y= lat, group = group),color = "white",
               size = 0, alpha = 0.9) + 
  geom_text(data = centers, aes(x=x, y=y, label=id),color="white", size = 3, alpha = 0.6) + 
  theme_void() + 
  scale_fill_manual(
    values = my_palette,
    name = "Average Percentage Colony Loss",
    guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                         label.position = "bottom", title.position = "top", nrow=1)) + 
  ggtitle("A Map of Percent Colony Loss During Colder Months by State in 2018") + 
  theme(
    legend.position=c(0.5, 0.9),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size=12, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4,
                                                                                     l = 2, unit = "cm")),
  )
```
```{r  State colony loss map during colder months in 2019}
loss_2019_coldmonths <- colony %>% 
  select(everything()) %>% 
  filter((Year == 2019) & (Quarter %in% c("Q1", "Q4"))) %>% 
  group_by(State, Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(avg_loss = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

summary(loss_2019_coldmonths)  

# map creation

map <- geojson_read("us_states_hexgrid.geojson", what = "sp")
map@data <-  map@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
map_fortified <- tidy(map, region = "google_name")

# calculating centroid of each hexagon and adding labels 

centers <- cbind.data.frame(data.frame(gCentroid(map, byid= TRUE), id=map@data$iso3166_2))

# merge geospatial and numerical data 
loss_2019_coldmonths_fortified <- map_fortified %>% 
  left_join(. , loss_2019_coldmonths, by=c("id" = "State"))

loss_2019_coldmonths_fortified

# prepare binning 
loss_2019_coldmonths_fortified$bin <- cut(loss_2019_coldmonths_fortified$avg_loss, breaks = c(seq(1,32,8), Inf), labels = c("1-8", "9-16", "17-24", "25+"), include.lowest=TRUE)

# colour scale from viridis color palette
my_palette <- rev(plasma(8))[c(-1,-8)]

# plotting 
ggplot() + 
  geom_polygon(data = loss_2019_coldmonths_fortified, aes(fill = bin, x = long, y= lat, group = group),color = "white",
               size = 0, alpha = 0.9) + 
  geom_text(data = centers, aes(x=x, y=y, label=id),color="white", size = 3, alpha = 0.6) + 
  theme_void() + 
  scale_fill_manual(
    values = my_palette,
    name = "Average Percentage Colony Loss",
    guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                         label.position = "bottom", title.position = "top", nrow=1)) + 
  ggtitle("A Map of Percent Colony Loss During Colder Months by State in 2019") + 
  theme(
    legend.position=c(0.5, 0.9),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size=12, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4,
                                                                                     l = 2, unit = "cm")),
  )
```
```{r  State colony loss map during colder months in 2020}

loss_2020_coldmonths <- colony %>% 
  select(everything()) %>% 
  filter((Year == 2020) & (Quarter %in% c("Q1", "Q4"))) %>% 
  group_by(State, Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(avg_loss = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

summary(loss_2020_coldmonths)  

# map creation

map <- geojson_read("us_states_hexgrid.geojson", what = "sp")
map@data <-  map@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
map_fortified <- tidy(map, region = "google_name")

# calculating centroid of each hexagon and adding labels 

centers <- cbind.data.frame(data.frame(gCentroid(map, byid= TRUE), id=map@data$iso3166_2))

# merge geospatial and numerical data 
loss_2020_coldmonths_fortified <- map_fortified %>% 
  left_join(. , loss_2020_coldmonths, by=c("id" = "State"))

loss_2020_coldmonths_fortified

# prepare binning 
loss_2020_coldmonths_fortified$bin <- cut(loss_2020_coldmonths_fortified$avg_loss, breaks = c(seq(1,32,8), Inf), labels = c("1-8", "9-16", "17-24", "25+"), include.lowest=TRUE)

# colour scale from viridis color palette
my_palette <- rev(plasma(8))[c(-1,-8)]

# plotting 
ggplot() + 
  geom_polygon(data = loss_2020_coldmonths_fortified, aes(fill = bin, x = long, y= lat, group = group),color = "white",
               size = 0, alpha = 0.9) + 
  geom_text(data = centers, aes(x=x, y=y, label=id),color="white", size = 3, alpha = 0.6) + 
  theme_void() + 
  scale_fill_manual(
    values = my_palette,
    name = "Average Percentage Colony Loss",
    guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                         label.position = "bottom", title.position = "top", nrow=1)) + 
  ggtitle("A Map of Percent Colony Loss During Colder Months by State in 2020") + 
  theme(
    legend.position=c(0.5, 0.9),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size=12, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4,
                                                                                     l = 2, unit = "cm")),
  )
```

```{r  State colony loss map during colder months in 2021}

loss_2021_coldmonths <- colony %>% 
  select(everything()) %>% 
  filter((Year == 2021) & (Quarter %in% c("Q1", "Q4"))) %>% 
  group_by(State, Year) %>% 
  mutate(tot_loss = sum(`Lost Colonies`)) %>% 
  mutate(avg_loss = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

summary(loss_2021_coldmonths)  

# map creation

map <- geojson_read("us_states_hexgrid.geojson", what = "sp")
map@data <-  map@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
map_fortified <- tidy(map, region = "google_name")

# calculating centroid of each hexagon and adding labels 

centers <- cbind.data.frame(data.frame(gCentroid(map, byid= TRUE), id=map@data$iso3166_2))

# merge geospatial and numerical data 
loss_2021_coldmonths_fortified <- map_fortified %>% 
  left_join(. , loss_2021_coldmonths, by=c("id" = "State"))

loss_2021_coldmonths_fortified

# prepare binning 
loss_2021_coldmonths_fortified$bin <- cut(loss_2021_coldmonths_fortified$avg_loss, breaks = c(seq(1,32,8), Inf), labels = c("1-8", "9-16", "17-24", "25+"), include.lowest=TRUE)

# colour scale from viridis color palette
my_palette <- rev(plasma(8))[c(-1,-8)]

# plotting 
ggplot() + 
  geom_polygon(data = loss_2021_coldmonths_fortified, aes(fill = bin, x = long, y= lat, group = group),color = "white",
               size = 0, alpha = 0.9) + 
  geom_text(data = centers, aes(x=x, y=y, label=id),color="white", size = 3, alpha = 0.6) + 
  theme_void() + 
  scale_fill_manual(
    values = my_palette,
    name = "Average Percentage Colony Loss",
    guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                         label.position = "bottom", title.position = "top", nrow=1)) + 
  ggtitle("A Map of Percent Colony Loss During Colder Months by State in 2021") + 
  theme(
    legend.position=c(0.5, 0.9),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size=12, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4,
                                                                                     l = 2, unit = "cm")),
  )
```


```{r  Backtracking -- plotting total colonies over time}
US_colony3 <- US_colony %>% 
  mutate(Date = str_c(Year, Quarter, sep=" "))

US_colony3 <- US_colony3 %>% 
  group_by(Year) %>% 
  mutate(colonies_mils = round((`Starting Colonies`/1000000), 2)) %>% 
  mutate(colonies_mils_avg = round((mean(colonies_mils)), 2))

US_colony3 <- US_colony3 %>% 
  filter(Quarter == "Q1")


US_colony3 %>% 
  ggplot(aes(group= 1)) + 
  geom_area(aes(x = Year, y= colonies_mils_avg), fill = "#f3c63c", linetype = 1, size = 1.5, colour = "#573307") +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_line(size = 2, linetype = "solid", color = "white"), panel.grid.minor = element_line(size = 2, linetype = "solid", color = "white"), axis.line = element_line(colour = "black")) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(x = 'Year', y='Number of Colonies (Millions)', title = 'Number of Bee Colonies in the US Over Time')+
  theme(plot.title = element_text(hjust = .5))

```

```{r Loading State Temperature Data; joining with colony data }

conso_temp <- read.csv("Conso Temp.csv")
conso_temp

conso_temp$Date <- str_replace(conso_temp$Date, "04", "")

conso_temp <- conso_temp %>% 
  rename(Year = Date)

colony <- colony %>% 
  group_by(State, Year) %>% 
  mutate(yr_losses = mean(`Percent Loss`)) %>% 
  arrange(State, Year)

colony3 <- colony

colony_temp <- inner_join(colony3, conso_temp, by = c("State", "Year"))

colony_temp <- colony_temp %>% 
  rename(Temp = Value)

```

```{r Plotting Temp vs Colony Loss}

sapply(colony_temp, class)
colony_temp$Year <- factor(colony_temp$Year)
colony_temp$State <- factor(colony_temp$State)

colony_temp %>% 
  ggplot(aes(x = Temp, y = `Percent Loss`)) + geom_point(color = "#65a7d6") + geom_smooth(method = lm, se = TRUE, color = "#8752bf") + 
  theme_bw() + 
  labs(x = 'Temp (F)', y='Percent Loss of Colonies', title = 'Relationship Between Average Yearly Temperature and Yearly Percent Colony Loss')+
  theme(plot.title = element_text(hjust = .5, size = 12)) 

col_temp <- lm(`Percent Loss` ~ Temp, data = colony_temp)
summary(col_temp)   # Multiple R-squared:  0.0211,	Adjusted R-squared:  0.02021  

# Temperature is correlated, but is not explaining much of the variance 
```

```{r   States with Most Colony Loss}

top_loss <- colony3 %>% 
  group_by(State) %>% 
  filter(Quarter == 'Q1') %>% 
  mutate(avg_perc_loss = round(mean(`Percent Loss`)),2) %>% 
  arrange(desc(`avg_perc_loss`)) %>% 
  filter(Year == "2015") %>% 
  select(State, avg_perc_loss)

top_10 <- top_loss[1:10,]
sapply(top_10, class)
top_10$State <- factor(top_10$State, levels = top_10$State)
top_10 <- top_10 %>% 
  arrange(desc(avg_perc_loss))

top_10 %>% ggplot(aes(x = State, y = avg_perc_loss, fill = State)) + geom_col() + coord_flip() +
  theme_bw() + 
  scale_fill_brewer(palette="BrBG") + 
  labs(x = 'State', y='Average Percent Loss of Colonies', title = 'States with the Highest Average Percentage Loss of Colonies in Winter from 2015-2021') + 
  theme(plot.title = element_text(hjust = .5, size = 10)) +
  geom_text(aes(label = avg_perc_loss, hjust = -0.2, vjust = 0.5))
```

```{r  States with Low Colony Loss} 

low_loss <- colony3 %>% 
  group_by(State) %>% 
  filter(Quarter == 'Q1') %>% 
  mutate(avg_perc_loss = round(mean(`Percent Loss`)),2) %>% 
  arrange(`avg_perc_loss`) %>% 
  filter(Year == "2015") %>% 
  select(State, avg_perc_loss)

low_10 <- low_loss[1:10,]
sapply(low_10, class)
low_10$State <- factor(low_10$State, levels = low_10$State)

low_10 %>% ggplot(aes(x = State, y = avg_perc_loss, fill = State)) + geom_col() + coord_flip() +
  theme_bw() + 
  scale_fill_brewer(palette="BrBG") + 
  labs(x = 'State', y='Average Percent Loss of Colonies', title = 'States with the Lowest Average Percentage Loss of Colonies in Winter from 2015-2021') + 
  theme(plot.title = element_text(hjust = .5, size = 10)) +
  geom_text(aes(label = avg_perc_loss, hjust = -0.2, vjust = 0.5))

```






